### PR TITLE
Make `igrmonty` compile with "iharm" model

### PR DESCRIPTION
**Pull request by rndsrc**

### CODE REVIEW

**Comment by gnwong** [comment]
Hi CK! I'm curious -- did this not compile with the iharm model before?

**Comment by rndsrc** [comment]
I used `clang`.  Maybe `gcc` is less restrict?  Anyway this should make the code more portable.

**Comment by gnwong** [comment]
CK, we're working on cross-validating this pull request now. Since this will take a bit of time (right now we're just running a bunch of different high resolution runs to compare), can you make sure not to add any new commits to this PR for now? Thanks!

**Comment by rndsrc** [comment]
Sure.  There are some new changes related to bias tuning (which actually change the logic).  But those are in a different branch and a different pull request.

**Pull request merged**
